# Generated by Django 2.2.17 on 2020-12-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20201215_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservartionhistory',
            name='booker',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
