# Generated by Django 2.2.17 on 2020-12-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservartionhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='LineUser',
        ),
        migrations.DeleteModel(
            name='ReservartionHistory',
        ),
    ]
